# Generated by Django 4.0.4 on 2022-06-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='postagem'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
