# Generated by Django 4.0.4 on 2022-05-20 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 10, 12, 28, 319161)),
        ),
    ]
