# Generated by Django 4.0.4 on 2022-05-20 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 13, 21, 46, 306101, tzinfo=utc)),
        ),
    ]
