# Generated by Django 4.0.4 on 2022-05-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
