# Generated by Django 4.0.4 on 2022-05-21 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_usuario_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 21, 3, 14, 27, 370177, tzinfo=utc), null=True),
        ),
    ]
