# Generated by Django 4.0.4 on 2022-05-22 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 10, 59, 56, 147661, tzinfo=utc), null=True),
        ),
    ]
