# Generated by Django 4.0.4 on 2022-05-22 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='vencimento',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 22, 11, 32, 12, 727793, tzinfo=utc), null=True),
        ),
    ]
