# Generated by Django 4.0.4 on 2022-05-18 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='produtos')),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codigo_de_barras', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome', 'marca'],
            },
        ),
    ]
